
-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
INSERT INTO user (id, username, email, password, address, firstname, lastname, inscription_date, max_loans, loans, current_loans, outdated_loans) VALUES (1, 'user', 'juba.tidaf@gmail.com','$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Rouen', 'Juba', 'TIDAF', '24/01/2018', 24, 0, 0, 0);
INSERT INTO user (id, username, email,password, address, firstname, lastname, inscription_date, max_loans, loans, current_loans, outdated_loans) VALUES (2, 'admin', 'gfl@acial.fr','$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Paris', 'Ghiles', 'FEGHOUL', NULL , 24, 0, 0, 0);

INSERT INTO authority (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO authority (id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO user_authority (user_id, authority_id) VALUES (1, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 2);

INSERT into documents (id,code,title,author,year,gender,empruntable,emprunte,nbEmprunt,nbEmprunt,localization,nbEmpruntTotal); values (1,'jv8','java8','jean','2014','prog',false,false,8,1,0)
